export const items = [
  {
    id: 1,
    name: "Joyce Gomora",
    blurb:
      "The formidable first wife trying to control the narrative and get revenge.",
    rating: 5,
    emoji: "👑",
    focus: "Revenge",
    images: "/revenge.jpg",
  },
  {
    id: 2,
    name: "Jonasi's Hidden Lives",
    blurb:
      "A second wife, a mistress, and a girlfriend completely unravel an empire.",
    rating: 4,
    emoji: "🤫",
    focus: "Secrets",
    images: "/mistresses.jpeg",
  },
  {
    id: 3,
    name: "The Opening Funeral",
    blurb:
      "The ultimate family reunion where everyone wears black and shares secrets.",
    rating: 5,
    emoji: "⚰️",
    focus: "Drama",
    images: "/funeral.jpeg",
  },
  {
    id: 4,
    name: "The Ultimate Downfall",
    blurb: "What happens when women organize against one very undeserving man.",
    rating: 5,
    emoji: "💥",
    focus: "Justice",
    images: "/downfall.jpg",
  },
  {
    id: 5,
    name: "The Will Reading",
    blurb:
      "Shocking discoveries leave the family fighting over an unexpected fortune.",
    rating: 4,
    emoji: "📜",
    focus: "Greed",
    images: "/1.jpeg",
  },
  {
    id: 6,
    name: "Behind Closed Doors",
    blurb:
      "The perfect couple hides a dark and messy truth from the public eye.",
    rating: 5,
    emoji: "🚪",
    focus: "Betrayal",
    images: "/2.jpeg",
  },
  {
    id: 7,
    name: "The Forbidden Alliance",
    blurb: "Two bitter rivals team up to take down a much bigger enemy.",
    rating: 4,
    emoji: "🤝",
    focus: "Strategy",
    images: "/3.jpeg",
  },
  {
    id: 8,
    name: "Whispers in the Dark",
    blurb: "An anonymous blackmailer threatens to ruin the family's good name.",
    rating: 5,
    emoji: "📱",
    focus: "Blackmail",
    images: "/4.jpeg",
  },
  {
    id: 9,
    name: "The Last Stand",
    blurb:
      "With their backs against the wall, the women make one final bold move.",
    rating: 5,
    emoji: "⚔️",
    focus: "Courage",
    images: "/5.jpeg",
  },
  {
    id: 10,
    name: "A Courtroom Climax",
    blurb:
      "Lies are exposed under oath as the legal battle reaches its boiling point.",
    rating: 4,
    emoji: "⚖️",
    focus: "Truth",
    images: "/6.jpeg",
  },
  {
    id: 11,
    name: "The Golden Cage",
    blurb:
      "Living in luxury means nothing when you are trapped by someone else's rules.",
    rating: 5,
    emoji: "🏰",
    focus: "Freedom",
    images: "/7.jpeg",
  },
  {
    id: 12,
    name: "New Beginnings",
    blurb: "The dust settles, and the survivors start over on their own terms.",
    rating: 5,
    emoji: "🌱",
    focus: "Healing",
    images: "/8.jpeg",
  },
];
